INSERT INTO Kilpailija (etunimi, sukunimi, kayttajatunnus, salasana, usergroup) VALUES ('Testi', 'Käyttäjä', 'testi', 'testi', 'superuser');
INSERT INTO Kilpailija (etunimi, sukunimi, kayttajatunnus, salasana, usergroup) VALUES ('Hamish', 'Craigmile', 'hcraigmile0', 'XvZNiUReNv', null);
INSERT INTO Kilpailija (etunimi, sukunimi, kayttajatunnus, salasana, usergroup) VALUES ('Cornell', 'Horsefield', 'chorsefield1', 'LjLMnlzIc', null);
INSERT INTO Kilpailija (etunimi, sukunimi, kayttajatunnus, salasana, usergroup) VALUES ('Noll', 'Ovendon', 'novendon2', 'HgxWRu9wGab', 'tuomari');
INSERT INTO Kilpailija (etunimi, sukunimi, kayttajatunnus, salasana, usergroup) VALUES ('Abbye', 'Renzini', 'arenzini3', 'sCmswLvc', 'superuser');
INSERT INTO Kilpailija (etunimi, sukunimi, kayttajatunnus, salasana, usergroup) VALUES ('Dayna', 'Critchley', 'dcritchley4', 'jg6qiTuF', 'superuser');
INSERT INTO Kilpailija (etunimi, sukunimi, kayttajatunnus, salasana, usergroup) VALUES ('Brandice', 'Overstall', 'boverstall5', 'l7MN2fIHrWc', 'tuomari');
INSERT INTO Kilpailija (etunimi, sukunimi, kayttajatunnus, salasana, usergroup) VALUES ('Pren', 'Rodgerson', 'prodgerson6', '4vVQF1y', null);
INSERT INTO Kilpailija (etunimi, sukunimi, kayttajatunnus, salasana, usergroup) VALUES ('Dannie', 'Calendar', 'dcalendar7', 'W9OtnWi', 'superuser');
INSERT INTO Kilpailija (etunimi, sukunimi, kayttajatunnus, salasana, usergroup) VALUES ('Eberto', 'Crayton', 'ecrayton8', 'fLaw7nbm', null);


INSERT INTO Kilpailu (pvm, paikka) VALUES ('2017-08-01', 'Helsinki');
INSERT INTO Kilpailu (pvm, paikka) VALUES ('1954-03-17', 'Shimonoseki');
INSERT INTO Kilpailu (pvm, paikka) VALUES ('1963-08-30', 'San José de Ocoa');
INSERT INTO Kilpailu (pvm, paikka) VALUES ('2006-09-21', 'Ilmajoki');
INSERT INTO Kilpailu (pvm, paikka) VALUES ('1978-10-10', 'Caldelas');
INSERT INTO Kilpailu (pvm, paikka) VALUES ('1958-09-09', 'Litvínovice');
INSERT INTO Kilpailu (pvm, paikka) VALUES ('2005-08-14', 'Horodyshche');
INSERT INTO Kilpailu (pvm, paikka) VALUES ('2009-06-30', 'Wleń');
INSERT INTO Kilpailu (pvm, paikka) VALUES ('1976-01-07', 'Wudan');
INSERT INTO Kilpailu (pvm, paikka) VALUES ('1948-05-20', 'Bélel');
INSERT INTO Kilpailu (pvm, paikka) VALUES ('1980-06-10', 'Cikeper');
INSERT INTO Kilpailu (pvm, paikka) VALUES ('1958-02-17', 'Jambulang');
INSERT INTO Kilpailu (pvm, paikka) VALUES ('1976-08-21', 'Karlstad');
INSERT INTO Kilpailu (pvm, paikka) VALUES ('1975-05-08', 'Salakuray');
INSERT INTO Kilpailu (pvm, paikka) VALUES ('1992-12-12', 'Mýto');
INSERT INTO Kilpailu (pvm, paikka) VALUES ('1924-03-16', 'Feyẕābād');
INSERT INTO Kilpailu (pvm, paikka) VALUES ('1965-10-22', 'Wulong');
INSERT INTO Kilpailu (pvm, paikka) VALUES ('1945-06-22', 'Kertai');
INSERT INTO Kilpailu (pvm, paikka) VALUES ('1928-11-26', 'Kamālia');
INSERT INTO Kilpailu (pvm, paikka) VALUES ('1997-05-06', 'Koronganayam');


INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (1, 'kolme taulua', 3, 1);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (1, 'in felis donec', 7, 13);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (11, 'vestibulum ante', 2, 19);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (8, 'vulputate luctus cum', 6, 18);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (9, 'nulla ut erat id mauris vulputate', 5, 8);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (22, 'penatibus et', 1, 1);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (9, 'quisque arcu libero rutrum ac lobortis', 1, 15);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (15, 'cubilia curae', 5, 2);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (16, 'consequat in consequat', 3, 2);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (21, 'dapibus duis at velit eu', 2, 4);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (19, 'vel lectus', 3, 2);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (13, 'erat nulla tempus', 4, 1);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (13, 'ligula pellentesque ultrices phasellus id', 8, 1);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (7, 'venenatis turpis enim blandit mi', 10, 15);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (24, 'vestibulum sagittis sapien cum sociis', 5, 15);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (23, 'lectus suspendisse potenti in', 10, 20);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (17, 'donec pharetra magna', 8, 19);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (23, 'sagittis sapien cum sociis natoque', 10, 2);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (18, 'praesent lectus vestibulum quam sapien varius', 1, 2);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (11, 'donec posuere', 9, 8);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (5, 'sed tristique in tempus', 8, 12);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (4, 'vulputate elementum nullam varius nulla facilisi', 8, 2);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (23, 'commodo vulputate justo in', 6, 2);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (9, 'primis in faucibus orci luctus', 3, 18);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (2, 'parturient montes', 1, 6);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (20, 'in faucibus orci', 4, 16);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (24, 'amet nunc viverra dapibus nulla', 2, 7);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (9, 'at feugiat non', 7, 3);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (11, 'nisi volutpat', 7, 7);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (3, 'ipsum integer a nibh', 9, 17);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (3, 'non mauris morbi non lectus', 10, 7);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (23, 'commodo vulputate justo', 10, 20);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (11, 'turpis elementum', 10, 16);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (2, 'magna bibendum imperdiet nullam orci pede', 1, 10);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (2, 'adipiscing elit proin interdum mauris', 10, 6);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (5, 'quis lectus suspendisse', 2, 12);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (7, 'fusce consequat nulla nisl nunc', 9, 4);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (1, 'congue etiam justo etiam pretium', 10, 20);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (20, 'suspendisse potenti cras', 2, 17);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (22, 'mollis molestie', 2, 5);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (15, 'rutrum rutrum neque aenean auctor gravida', 8, 12);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (9, 'in ante vestibulum ante ipsum primis', 2, 14);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (12, 'placerat praesent blandit nam nulla integer', 1, 12);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (2, 'tempus sit amet', 5, 9);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (23, 'est et tempus semper est', 7, 19);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (4, 'sapien urna pretium', 6, 15);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (23, 'laoreet ut rhoncus', 4, 16);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (16, 'faucibus cursus urna', 9, 19);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (21, 'lobortis sapien sapien', 1, 17);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (8, 'sagittis nam congue', 6, 12);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (6, 'duis mattis egestas metus', 6, 5);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (5, 'vivamus metus', 7, 19);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (7, 'sed nisl', 9, 2);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (24, 'proin at turpis', 7, 15);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (2, 'sed sagittis nam congue risus', 10, 20);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (9, 'bibendum felis sed interdum venenatis turpis', 1, 1);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (18, 'luctus rutrum nulla', 6, 9);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (13, 'rutrum rutrum neque', 10, 8);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (15, 'platea dictumst maecenas ut massa quis', 7, 15);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (18, 'sit amet diam in magna bibendum', 3, 14);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (24, 'morbi ut', 9, 16);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (2, 'morbi non lectus aliquam sit', 2, 20);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (25, 'semper sapien a', 3, 9);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (6, 'in tempus sit amet sem fusce', 10, 3);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (18, 'sociis natoque penatibus et magnis', 8, 5);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (20, 'magnis dis parturient montes', 4, 20);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (10, 'augue vestibulum ante ipsum', 5, 16);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (9, 'mauris vulputate elementum nullam varius nulla', 3, 7);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (8, 'ac neque', 1, 19);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (23, 'tellus in sagittis dui', 5, 11);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (6, 'mus vivamus vestibulum sagittis sapien cum', 3, 3);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (19, 'pellentesque volutpat', 6, 8);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (17, 'ultrices posuere cubilia curae duis faucibus', 5, 1);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (9, 'natoque penatibus et', 2, 12);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (16, 'quis orci eget', 9, 14);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (12, 'vulputate nonummy maecenas tincidunt lacus', 6, 17);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (23, 'a suscipit nulla elit', 7, 2);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (2, 'aliquet pulvinar sed nisl nunc', 1, 10);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (22, 'nisl ut volutpat sapien arcu', 8, 17);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (6, 'in tempor', 6, 7);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (17, 'euismod scelerisque quam turpis', 2, 12);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (6, 'id turpis integer aliquet massa', 1, 15);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (23, 'eu mi nulla', 9, 8);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (15, 'ipsum primis in faucibus orci luctus', 9, 11);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (8, 'lacinia eget tincidunt', 8, 8);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (4, 'lacus morbi quis tortor id nulla', 2, 20);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (2, 'mauris non', 2, 19);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (23, 'sed tincidunt eu felis fusce', 9, 18);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (20, 'sodales scelerisque mauris sit amet eros', 6, 18);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (1, 'accumsan felis ut at dolor', 5, 5);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (7, 'maecenas pulvinar lobortis est phasellus sit', 5, 9);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (9, 'erat eros viverra eget', 6, 20);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (23, 'penatibus et magnis dis', 7, 17);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (5, 'pharetra magna ac consequat metus', 9, 19);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (16, 'posuere cubilia', 5, 2);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (5, 'risus auctor', 4, 12);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (21, 'duis bibendum morbi non quam', 7, 11);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (23, 'adipiscing molestie hendrerit at vulputate', 8, 20);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (20, 'nulla ultrices aliquet maecenas', 8, 1);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (20, 'rhoncus aliquet', 9, 14);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (3, 'nulla facilisi cras non velit', 9, 11);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (19, 'in magna bibendum', 3, 4);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (23, 'sem mauris', 2, 5);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (10, 'sollicitudin mi sit amet', 2, 16);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (13, 'pretium iaculis diam erat', 8, 13);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (9, 'in sagittis', 1, 15);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (14, 'sapien a libero nam', 8, 18);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (7, 'in congue etiam justo etiam', 6, 2);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (5, 'eget rutrum at lorem', 3, 20);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (15, 'iaculis diam erat fermentum justo nec', 5, 17);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (22, 'quisque ut erat curabitur gravida', 2, 2);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (8, 'mauris enim', 2, 12);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (10, 'justo pellentesque viverra', 8, 14);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (6, 'velit donec diam', 10, 3);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (22, 'sollicitudin vitae', 7, 19);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (5, 'eu orci mauris lacinia sapien quis', 6, 4);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (25, 'convallis nunc proin', 5, 17);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (22, 'cras mi pede malesuada in', 6, 2);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (5, 'habitasse platea', 10, 2);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (2, 'cubilia curae', 9, 5);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (23, 'amet lobortis', 8, 2);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (25, 'luctus nec molestie sed justo', 8, 10);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (11, 'rhoncus aliquet pulvinar sed nisl', 8, 18);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (12, 'massa quis augue luctus tincidunt', 8, 3);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (6, 'orci pede venenatis non sodales', 5, 17);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (7, 'vitae nisl aenean', 3, 13);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (18, 'varius nulla', 5, 19);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (18, 'lacus morbi quis tortor id', 7, 11);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (6, 'nunc purus phasellus in felis donec', 6, 18);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (1, 'etiam pretium iaculis justo in', 3, 15);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (6, 'morbi odio', 8, 5);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (17, 'ut massa quis augue luctus', 3, 7);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (24, 'morbi vel lectus in quam fringilla', 1, 7);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (9, 'posuere nonummy integer non', 2, 12);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (9, 'natoque penatibus', 10, 12);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (4, 'etiam justo etiam pretium', 9, 10);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (6, 'sapien cursus vestibulum proin eu', 3, 19);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (6, 'libero ut', 2, 7);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (21, 'accumsan tellus nisi eu orci mauris', 7, 3);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (3, 'non quam nec dui luctus rutrum', 3, 10);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (3, 'id consequat in consequat ut nulla', 3, 9);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (17, 'blandit lacinia erat vestibulum sed magna', 2, 19);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (8, 'felis fusce posuere felis sed', 9, 15);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (19, 'in hac habitasse platea', 8, 16);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (3, 'lorem quisque', 1, 15);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (8, 'id mauris vulputate', 6, 13);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (5, 'felis sed lacus', 9, 7);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (12, 'risus dapibus augue vel', 9, 17);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (18, 'sit amet', 4, 4);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (13, 'dapibus nulla suscipit ligula in', 6, 1);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (22, 'felis fusce posuere felis sed', 7, 20);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (8, 'vulputate vitae nisl aenean', 1, 11);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (11, 'eget eleifend luctus ultricies eu nibh', 4, 1);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (11, 'duis bibendum', 8, 9);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (15, 'elit proin risus praesent', 1, 18);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (8, 'sagittis dui vel nisl', 1, 11);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (3, 'nulla nisl nunc nisl', 7, 6);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (1, 'vestibulum ante ipsum primis', 5, 8);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (19, 'suspendisse potenti in eleifend quam', 1, 18);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (18, 'convallis nunc proin at turpis a', 9, 10);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (13, 'proin risus praesent lectus vestibulum', 2, 6);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (3, 'lorem quisque ut', 1, 17);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (24, 'urna ut tellus nulla ut erat', 1, 14);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (22, 'proin eu mi nulla ac enim', 6, 11);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (11, 'massa tempor', 2, 14);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (20, 'maecenas tristique est et tempus', 4, 1);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (11, 'odio donec vitae nisi nam', 7, 7);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (2, 'semper est quam', 2, 12);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (17, 'vestibulum aliquet ultrices erat tortor sollicitudin', 4, 2);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (9, 'tortor duis', 1, 11);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (13, 'at nulla', 6, 1);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (5, 'quam nec dui luctus rutrum nulla', 6, 16);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (15, 'lectus pellentesque eget nunc donec', 6, 1);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (8, 'morbi sem', 10, 7);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (16, 'metus aenean fermentum donec ut', 2, 16);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (13, 'magna bibendum imperdiet nullam orci pede', 3, 14);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (19, 'praesent blandit lacinia', 5, 14);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (14, 'id luctus nec molestie sed justo', 6, 8);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (2, 'nunc vestibulum ante', 7, 10);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (19, 'erat quisque erat eros', 10, 9);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (14, 'at turpis donec', 2, 10);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (19, 'in quam fringilla rhoncus', 9, 7);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (2, 'lacus at turpis', 7, 8);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (19, 'at ipsum ac tellus semper interdum', 6, 6);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (7, 'ultrices phasellus id sapien', 6, 7);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (17, 'donec quis', 7, 20);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (10, 'risus dapibus augue vel accumsan tellus', 7, 7);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (2, 'felis sed lacus morbi sem mauris', 10, 8);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (2, 'et commodo vulputate justo in', 9, 7);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (7, 'nunc nisl duis bibendum felis', 3, 10);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (17, 'eros vestibulum ac est lacinia nisi', 3, 15);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (5, 'praesent blandit nam', 8, 1);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (17, 'auctor gravida sem praesent', 4, 13);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (7, 'malesuada in imperdiet et', 1, 12);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (6, 'felis ut at', 5, 13);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (9, 'semper porta volutpat quam', 10, 10);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (11, 'quis augue', 10, 20);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (7, 'sapien cursus vestibulum proin eu mi', 8, 12);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (18, 'sapien cursus vestibulum proin eu', 9, 12);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (8, 'rutrum at lorem integer tincidunt', 6, 1);
INSERT INTO Rasti (rastinro, kuvaus, taululkm, kilpailu) VALUES (12, 'feugiat non pretium', 8, 12);


INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 6);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 6);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 6);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 6);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 6);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 6);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 6);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 6);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 6);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 6);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 6);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 6);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 6);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 6);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 6);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 6);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 20);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 13);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 6);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 16);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 6);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 5);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 1);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 4);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (3, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (5, 10);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 15);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 17);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (1, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 19);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 9);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 8);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 14);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 6);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (7, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (9, 18);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (8, 11);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 7);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (2, 3);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (4, 12);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (6, 2);
INSERT INTO Osallistuminen (kilpailija, kilpailu) VALUES (10, 7);


