-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kilpailija CASCADE;
DROP TABLE IF EXISTS Kilpailu CASCADE;
DROP TABLE IF EXISTS Rasti CASCADE;
DROP TABLE IF EXISTS Tulos CASCADE;
DROP TABLE IF EXISTS Osallistuminen CASCADE;